#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-fill --randomize ~/Wallpapers/* & 
~/.local/bin/ext_mon_only.sh & 
~/.config/polybar/launch.sh & 
picom -b & 
light -S 40 & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config single_monocle 	     true
bspc config focus_follows_pointer true

bspc rule -a Firefox desktop='^2'
bspc rule -a Discord desktop='^2'
