#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
feh --bg-fill --randomize ~/Wallpapers/Mountains/* & 
picom --experimental-backends & 
light -S 40 & 

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config single_monocle 	 true

bspc rule -a Firefox desktop='^2'
bspc rule -a Discord desktop='^2'
