unbind r 
bind r source-file ~/.config/tmux/tmux.conf

# globals stuff 
set -g prefix C-x
set -g mouse on 
set -g base-index 1 
set -g renumber-windows on
set-option -g status-position top

bind -r m resize-pane -Z 

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# splits
unbind '"'
unbind %
bind | split-window -h
bind _ split-window -v

# copy mode 
set-window-option -g mode-keys vi 
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

# plugins 
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'jimeh/tmux-themepack'

# theme stuff 
set-option -g default-terminal 'screen-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g @themepack 'powerline/default/gray'

run '~/.tmux/plugins/tpm/tpm'
