add_newline = true

[character]
success_symbol = "[⌃](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[⌃](bold red)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

[lua]
format = "via [ $version](bold blue)"

